{"time":"2025-04-04T14:35:44.7237445+09:00","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"D:\\Code\\Machine Translation\\wandb\\run-20250404_143544-mmmusg1b\\logs\\debug-core.log"}
{"time":"2025-04-04T14:35:44.8339818+09:00","level":"INFO","msg":"created new stream","id":"mmmusg1b"}
{"time":"2025-04-04T14:35:44.8339818+09:00","level":"INFO","msg":"stream: started","id":"mmmusg1b"}
{"time":"2025-04-04T14:35:44.8339818+09:00","level":"INFO","msg":"writer: Do: started","stream_id":"mmmusg1b"}
{"time":"2025-04-04T14:35:44.8339818+09:00","level":"INFO","msg":"handler: started","stream_id":"mmmusg1b"}
{"time":"2025-04-04T14:35:44.8339818+09:00","level":"INFO","msg":"sender: started","stream_id":"mmmusg1b"}
{"time":"2025-04-04T14:35:45.6074871+09:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-04-04T14:35:45.8025206+09:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-04-04T14:35:49.7881408+09:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-04-04T14:36:34.9840434+09:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.101.152.150:58936->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-04T14:36:37.2596555+09:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/baoxihuang0429/Fintuning-QA-Bert/mmmusg1b/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
